# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89d836abf554456795d78b565d9d3d749f5f8eaea4840cd13706df325dcca8568ecde8e5abaf24e41e786fe80f946be07a2919d5650bfef6223c153e69bdef9c

test:
  secret_key_base: 7b380047e33eaee9405e2a1c980cd1061ca9fc469c9a5688ea961cf756d04e293907ea11db603539b694517f5af9d1318e7e76b9dde7b258deb4e1360a437c1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
